# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
