# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_auto_20160411_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
