# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_auto_20160412_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.Priority_Mission'),
        ),
    ]
