# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_mission_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Task')),
                ('users_enrolled', models.ManyToManyField(to='missions.UserProfile')),
            ],
        ),
    ]
